### ISSUE TITLE
Wrong Windows Installation Folder

### ISSUE THREAD

**Issue by m-planck** [fangq/mcx#105]
The installer uses the wrong windows installation folder on a x86-64 platform. MCXstudio frontend and mcx backend are compiled as 64 bit executables. However, the MCXStudio-v2020-installer.exe is 32 bit only. So the installer writes everything to the wrong folder "C:\Program Files (x86)" where it should be "C:\Program Files\". 32 bit programs are redirected to the "C:\Program Files (x86)\" folder by WOW64 (Windows-On-Windows 64-bit) , executables inside this folder do only see 32bit version of libraries, system etc. This could be a reason of unexpected crash on calling system functions.

Possible fix: Compiling installation packet with 64bit installer or manually changing installation path to "C:\Program Files\"

**Comment by fangq** [comment]
@m-planck, I was just about to announce a new release - 
the above patch seems to have fixed the installation path, if possible, can you try this installer? 

I did not see any adverse effect on windows when it was installed to the x86 folder, however, I agree with you it probably be better in the 64bit folder (mcxstudio.exe is 32bit, but mcx/mcxcl/mmc are 64bit).

**Comment by m-planck** [comment]
@fangq Thanks for the quick fix. mcxstudio.exe is a 64bit too on my system

The installer uses still a wrong folder for the start menu shortcut (program group):
C:\ProgramData\Microsoft\Windows\Start Menu\Programs\(Default)\
 where it should be 
C:\ProgramData\Microsoft\Windows\Start Menu\Programs\MCXStudio v2020\

**Comment by fangq** [comment]
icon group path should be fixed in this newly built installer

http://mcx.space/nightly/win64/MCXStudio-v2020-installer.exe
