### ISSUE TITLE
Remote SSH server connect error

### ISSUE THREAD

**Issue by m-planck** [fangq/mcx#109]
On connecting to an external ssh server you get following error in the MCX Studio output:

Disconnected: Server protocol violation: unexpected SSH2_MSG_UNIMPLEMENTED packet

Solution:
The plink and pscp executables coming with the MCX Installer packet are too old. Go to https://www.chiark.greenend.org.uk/~sgtatham/putty/latest.html and use the latest 64bit binaries, overwriting the installed ones.

Plattform: Windows 10 2004 x64

**Comment by fangq** [comment]
thanks @m-planck. I updated my nightly build script as well as the included putty exe. Please try the latest installer/nightly build zip package and see if this issue is still there.

http://mcx.space/nightly/win64/
