### ISSUE TITLE
Question about MCX Cloud "Preview"

### ISSUE THREAD

**Issue by syuys** [fangq/mcx#119]
Hi, thanks for releasing a very convenient cloud for global users.

I tried the newly released MCX Cloud today. I just wondered why the input json made the preview image look like this. The cylinder was not in the grid, which I expect that the cylinder would be on the edge of grid in each side.
<img src="https://user-images.githubusercontent.com/32219941/125072838-af6d9f00-e0ed-11eb-8847-125c24f7c391.png" width=65% height=65%>

My "Cylinder" setting in "Shapes" item is as follows. The OriginType is set to "True" in this input (not in this picture). And the "Dim" is simply set by [4, 4, 4] (not in this picture).
<img src="https://user-images.githubusercontent.com/32219941/125074367-c8774f80-e0ef-11eb-8d2b-7a00657bdcec.png" width=55% height=55%>

Thank you.

**Comment by fangq** [comment]
@syuys, thanks for reporting this - yes, this is a known issue and you can safely ignore the portion of the shapes outside of the domain. MCX rasterizes the shapes only within the space overlapping with the "Grid" construct, anything outside will be ignored. Also, if two objects occupies the same space, MCX actually use the "later" object in the Shapes list to overwrite the earlier objects. 

Ideally, this should be done via CSG (Constructive solid geometry)  feature of webgl/opengl to create more accurate renderings of the shapes, but at this point, this rendering only works for simple shapes, and need to be further polished in complex domains.

 by the way, same issue happens in `mcxpreview.m` as well as MCX Studio shape renderings.

I will leave this ticket open for now - if anyone is familiar with WebGL/OpenGL CSG and can help implement this improvement, that would be much appreciated.

**Comment by syuys** [comment]
@fangq thanks for your reply !

So, could I understand your explanation in the sense that the two sides of cylinder, in practical simulation, would be on the edge of my 4*4*4 grid based on the above input json ? Cuz in the begining I want to use the "Preview" function to check if my setting of tissue shape is correct or not.

Thanks.

**Comment by fangq** [comment]
@syuys, the units in all shape constructs are in voxels - in your case, your 4x4x4 voxelated domain will be too coarse to represent the cylindrical shapes.

you will have to increase the grid `Dim` and scale everything by the larger dimension size; then set `LengthUnit` (i.e. the voxel size) so that your domain length remains the same.

**Comment by syuys** [comment]
@fangq, ok. I understand. 

Thanks for your help and kind explanation.

**Comment by fangq** [comment]
@syuys, now I see the problem - the cylinder was correctly defined, but the rendering was incorrect.

here is direct link to [the example](http://mcx.space/cloud/index.html?tab=preview&data=N4Ig9gDgLglmB2BnEAuUMDGCA2MBGqIAZglAIYDuApomALZUCsIANOHgFZUZQD62ZAJ5gArlELwwAJzplsrEIgAWYCrypSp05ChAx4UDWR5x4CqEqoNCiCNyhSqCybzIATNzFgI5vCFrspWBpUBxEqNg5aMzQQAGUaRFNUUABJABFCOgwADwUABRUoBB0ARgAGSsq2dLAAWRhEWSgMJVCpcJqwAEExMAAVJUd3ds6QWriyADcqADUwbBFrFDCI8bB8siCYOU2LUbXagDlpWVwALycVjsOwSZmAJSoiVCI5RFv7qgBRHK9X96faZUBJUNwA7AfLrpADCcQhUPWcTsGBEAikBxqVDwIgA5gAxAS4wgKL7pMjkOpkRAAaxJbAA8mIIGJ8acKRIYDAFEyoCyoP1BHZCHk2A8jgBxUHglClABsABYABwAZhVjEYpSVAF82GypBQtjLQP1yqhymx+qVUIwqABaACcNXEKFtjt1IAZ0DAbiuoDioikGD9IEFwt0dngGBg8jY+TAOgA2iqLSmWOUALo1GAYlCJi0W0pZkCbKRkOjWvMF9Pp4ul8sAJlQ+ZrBeL+McAEdwlHBOaPekqIYeNJmxmPXElGQ7EnQBKpDBjaGyMTZWw4jBLs2FSwdwrx7rQDDBLh4L7cyaV6hSmwYWa8w2aw3izDK4nHzvn2Lr9rtcXarI+gpJ6C64voYZXKs2Z0M2coWnBLBwcWAAyVDwLiFgAKrwP8a4gHUYI7PqzSEHggiGAo8yLAw+IxlcIAKARnhkM2oB0CILEoBaIDsTo3GrjeIAxKUh48Rx5psLxEkgAJbDCX+v6/kAA==).

I am looking into this.

**Comment by syuys** [comment]
@fangq thanks.

**Comment by fangq** [comment]
the offset should be fixed now with my above patch.
