### ISSUE TITLE
MCX Monte Carlo eXtreme No Output to Matlab 

### ISSUE THREAD

**Issue by FarmanHassan** [fangq/mcx#122]
i need help to link mcx with matlab my matlab is 2020a

**Comment by FarmanHassan** [comment]
@fangq  can you help please

**Comment by fangq** [comment]
@FarmanHassan, your question did not give enough detail for anyone to help.

if you did not get the output you needed, please describe the details so that developers can reproduce the issue. Please post your sample code, data and conditions (OS, mcx versions etc.)

**Comment by FarmanHassan** [comment]
Sorry sir

The system is windows 10 21h1
Matlab is R2020a
Graphic card is RTX 2070 Super
I installed the driver and CUDA

I am using internal examples but i want to see the output in matlab 
I added windows paths and using matlab path tool i added mcx and its subfolders 

When i open any examples validate and run after that in plot I click plot fluence mc2
It have error ( specified file dose not exist)
![image](https://user-images.githubusercontent.com/91091729/134142888-4d8bf773-15a1-482c-b948-49f306d2b4c5.jpeg)

![image](https://user-images.githubusercontent.com/91091729/134142946-7ea0e90a-aece-43a7-a946-9f040bdbdb36.jpeg)

**Comment by fangq** [comment]
in the middle of the window, there is an option called "Output format", it is by default set to "nii", therefore, you should choose the first item in the menu "Plot fluence (nii)" instead of the mc2 output.

**Comment by FarmanHassan** [comment]
Dear sir I appreciate your help
But when I click plot fluence mc2 it gives this result 
I want to see the output in matlab 
Maybe i made mistakes in inshallan. Can you help me?
