### ISSUE TITLE
integration of MCXlab in brainstorm

### ISSUE THREAD

**Issue by Edouard2laire** [fangq/mcx#124]
Hello Dr Fang, 

I am contacting you as I am currently updating our nirs package nirstorm which is relying on MCXlab for fluences computation. 
Nirstorm (https://github.com/Nirstorm/nirstorm) is a Matlab-based open-source package for nirs analysis and is integrated as a plugin inside Brainstorm. 

Currently, to use Mcxlab functionalities, we are asking the users to download mcxlab from your website and to add it to their Matlab path which is not very practical. Additionally, it's not possible for users who don't have Matlab to use that solution in the compiled version of brainstorm. 

I was therefore wondering if you would agree to add Mcxlab as a plugin inside brainstorm (similarly to iso2mash also shipped within Brainstorm). 

if you agree, I can make the PR in the brainstorm repository. 

note: you will be able to track the number of installations using a similar link as: https://neuroimage.usc.edu/bst/pluglog.php?c=K8Yda7B&plugname=nirstorm&action=install&list=1 (here tracking the number of installations of nirstorm)

Regards, 
Edouard

**Comment by fangq** [comment]
@Edouard2laire, I don't see any problem adding mcxlab as a plug-in to NIRSTORM given both are GPLv3 licensed.

the only decision you may want to think about is whether to integrate mcxlab or mcxlabcl - mcxlabcl can use a wider range of hardware, including CPUs, but its speed is not as fast on NVIDIA GPUs compared to mcxlab (cuda) - if it helps, feel free to include both and use `mcxlab(...,'cuda')` or `mcxlab(...,'opencl') to choose.

for mcxlab post-processing, it may need matlab functions from [mcx/utils](https://github.com/fangq/mcx/tree/master/utils)

Also, as a plugin, I assume you will include the precompiled mex files for various platforms?

**Comment by Edouard2laire** [comment]
Hello, 

Thanks a lot for your reply. I opened a PR here: https://github.com/brainstorm-tools/brainstorm3/pull/440
> Also, as a plugin, I assume you will include the precompiled MEX files for various platforms?

Yes, I am currently downloading the MEX files from the following link for Linux/Windows and Mac:            http://mcx.space/nightly/release/v2020/mcxlab-linux-x86_64-v2020.zip
http://mcx.space/nightly/release/v2020/mcxlab-osx-x86_64-v2020.zip
http://mcx.space/nightly/release/v2020/mcxlab-win-x86_64-v2020.zip

Is that ok? 
About your previous question, yes it would be a good option to be able to use both the Cuda and the OpenCL option. However, it seems that the MXClab archive only contains the Mex files for the Cuda option. I there an archive containing everything?


If you can, we can continue the discussion either here, or in the brainstorm PR
Edouard

**Comment by fangq** [comment]
closing this ticket, continue the discussions at brainstorm-tools/brainstorm3#440
