### ISSUE TITLE
MCX tutorials and training materials

### ISSUE THREAD

**Issue by Nawroz82** [fangq/mcx#130]
I am PhD student, I want to learn MCX for my research, is there any training course How I learn?

**Comment by fangq** [comment]
hi @Nawroz82, please browse the training materials we posted on mcx's wiki: http://mcx.space/wiki/. If you want to use the GUI tools, please browse this page for video tutorials
http://mcx.space/wiki/index.cgi?Demo/MCXStudio

also, we have recently released an online simulation platform - MCX Cloud, please see tutorials on this page

http://mcx.space/cloud/

**Comment by Nawroz82** [comment]
Thanks a lot 🌺🌺🌺🌺



Sent from myMail for iOS


Monday, 15 November 2021, 10:13 PM +0300 from ***@***.***  ***@***.***>:
>hi  @Nawroz82 , please browse the training materials we posted on mcx's wiki:  http://mcx.space/wiki/ . If you want to use the GUI tools, please browse this page for video tutorials
>http://mcx.space/wiki/index.cgi?Demo/MCXStudio
>also, we have recently released an online simulation platform - MCX Cloud, please see tutorials on this page
>http://mcx.space/cloud/
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>Triage notifications on the go with GitHub Mobile for  iOS or  Android .
-- 
Brighten Your Future with Erbil Polytechnic University  EPU


epu.edu.iq 
<http://epu.edu.iq>
