### ISSUE TITLE
not able to connect Mcx studio with the octave

### ISSUE THREAD

**Issue by mcxstudio** [fangq/mcx#141]
I want to see the output of the simulated model in octave but it is not able to load the data into octave
I have followed the procedure which you have mentioned in the tutorials of Mcx Studio
![Screenshot (3)](https://user-images.githubusercontent.com/101257493/157429848-6d1da84b-423c-4fea-9397-47f351c3d273.png)

**Comment by fangq** [comment]
for octave on windows, you will have to manually add path to the related folders, including
```
MCXStudio/MATLAB/mcxlab
MCXStudio/MATLAB/mcxlabcl
MCXStudio/MATLAB/mmclab
MCXStudio/MCXSuite/mcx/utils
MCXStudio/MCXSuite/mmc/matlab
MCXStudio/MCXSuite/mcxcl/utils
```

Adding path can be [done automatically in the installer script](https://github.com/fangq/mcx/blob/master/inno/MCXStudio.iss#L322-L331) for MATLAB, but can't be done for octave.
