### ISSUE TITLE
normalized parameters or 3-dimensional matrix parameters

### ISSUE THREAD

**Issue by juzhongren** [fangq/mcx#145]
Excuse me, does this program include normalized parameters, parameters that remove the time dimension, and parameters that are saved as a 3-dimensional matrix? There is no need to use matlab or python for data processing, thank you

**Comment by fangq** [comment]
sorry, I don't fully understand your question. can you provide more information what you want to know?

**Comment by juzhongren** [comment]
Sorry for not stating clearly.
&nbsp; &nbsp; What I mean is that the parameter package that generates the data does not include normalizing these output values, such as output flux, F - fluence, E - energy density, I don't need to re-read the data through matlab or python for normalization.
&nbsp; &nbsp; &nbsp;Another question is whether there is a parameter setting. The time dimension of the data I generate is 1, and the output data that includes the time dimension needs to be reduced to 3-dimensional data that does not include time.
&nbsp; &nbsp; &nbsp;I can also process data through matlab or python. I just want to ask if these functions are set up. If so, I don’t have to do repeated work. Forgive my limited English. I don’t have an optics background, so I don’t understand some places. . Looking forward to your reply.





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fangq/mcx"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月3日(星期天) 晚上10:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fangq/mcx] normalized parameters or 3-dimensional matrix parameters (Issue #145)





 
sorry, I don't fully understand your question. can you provide more information what you want to know?

**Comment by fangq** [comment]
@juzhongren, I suggest you take a look at this section of the README

https://github.com/fangq/mcx#output-files

mcx standalone executable produces output in .mc2 or .jnii file, you will need to use whatever tool you prefer to read it.

if you want to disable normalization, you will need to use the `-U 0`, again, please read the command line options in the README

https://github.com/fangq/mcx#running-simulations

if you do not need time-resolved simulations, simply set your time step `Dt` the same as `T1` in the `Forward` section of the json input file, see

https://github.com/fangq/mcx#using-json-formatted-input-files

**Comment by juzhongren** [comment]
Dr. Qian, I ask you a question about the MCX parameters. I set the parameters to -O E -F nii %*. Is normalization enabled by default? -U [1|0] (--normalize) 1 to normalize flux to unitary; 0 save raw, as if the parameter was set to -O E -U 1 -F nii %*. Are the two outputs the same? I tried several times in the GUI, if DoNormalization is true, the output is a small number, if it is false, the output is a very large number.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fangq/mcx"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月4日(星期一) 凌晨0:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fangq/mcx] normalized parameters or 3-dimensional matrix parameters (Issue #145)





 
Closed #145.
