### ISSUE TITLE
C++ Error: input media optical properties are less than the labels in the volume

### ISSUE THREAD

**Issue by JyangOptics** [fangq/mcx#148]
it happens when running demo_mxlab_2d.m

**Comment by fangq** [comment]
what OS? mcx version? GPU model? driver version?

it works fine on my machine. did you try nightly-build? http://mcx.space/nightly/

![demo_mcxlab_2d](https://user-images.githubusercontent.com/226913/165676447-386f47ca-fdd4-419b-88ce-f4703df90bd4.png)

**Comment by JyangOptics** [comment]
> what OS? mcx version? GPU model? driver version?
> 
> it works fine on my machine. did you try nightly-build? http://mcx.space/nightly/
> 
> ![demo_mcxlab_2d](https://user-images.githubusercontent.com/226913/165676447-386f47ca-fdd4-419b-88ce-f4703df90bd4.png)

win 10, NVIDIA GeForce GTX 1660 Ti
mcx Version: 1.9.0 (v2021.2, Glossy Gluon)

**Comment by JyangOptics** [comment]
> > what OS? mcx version? GPU model? driver version?
> > it works fine on my machine. did you try nightly-build? http://mcx.space/nightly/
> > ![demo_mcxlab_2d](https://user-images.githubusercontent.com/226913/165676447-386f47ca-fdd4-419b-88ce-f4703df90bd4.png)
> 
> win 10, NVIDIA GeForce GTX 1660 Ti mcx Version: 1.9.0 (v2021.2, Glossy Gluon)

It works in nightly built version. but I found another problem: I am trying to use cfg.srctype = 'hyperboloid', but it lead to C++ Error: the specified source type is not supported.

**Comment by fangq** [comment]
@JyangOptics, I can set `cfg.srctype = 'hyperboloid'` using nightly build. Please check to see if the latest mcx mex file was added to your search path, type `which mcx` to see if it points to the nightly build folder.
