### ISSUE TITLE
mcxlab error: all CUDA-capable devices are busy or unavailable

### ISSUE THREAD

**Issue by zyrdegit** [fangq/mcx#153]
MCXLAB ERROR -46 in unit mcx_core.cu:2573: all CUDA-capable devices are busy or unavailable
Error from thread (0): all CUDA-capable devices are busy or unavailable
C++ Error: MCXLAB Terminated due to an exception!

**Comment by zyrdegit** [comment]
gpuinfo= mcxlab("gpuinfo")
Launching MCXLAB - Monte Carlo eXtreme for MATLAB & GNU Octave ...
error usage of mcx
Input must be a structure.
error mcxlab (line 429)
    [varargout{1:max(1,nargout)}]=mcx(varargin{1});

**Comment by fangq** [comment]
kill MATLAB and restart it usually solve this

**Comment by zyrdegit** [comment]
but it does not work

**Comment by fangq** [comment]
without any detail, I can't help.

**Comment by zyrdegit** [comment]
How to   set up "repetition"?I can find it in "maclab.m"

**Comment by fangq** [comment]
https://github.com/fangq/mcx/blob/master/mcxlab/mcxlab.m#L74
