### ISSUE TITLE
cloud-based version exemples return parse errors and display crashes

### ISSUE THREAD

**Issue by PyMarc2** [fangq/mcx#161]
When loading the top 5 examples, each of them return a parseerror.
Additionally, the browser says:

`Uncaught ReferenceError: jdata is not defined`

Tested with:
Google Chrome 110.0.5481
Firefox 110.0

**Comment by fangq** [comment]
@PyMarc2, the jdata error should be fixed by the above commit. let me know if you still see parseerror - I don't see it on my Chrome on Linux.

**Comment by PyMarc2** [comment]
yes, it fixed it. Thank you!
