### ISSUE TITLE
desktop version on macos seems brokem

### ISSUE THREAD

**Issue by PyMarc2** [fangq/mcx#162]
Under MacOS Montery 12.4
Desktop version won't launch.

<img width="276" alt="Screen Shot 2023-03-04 at 2 02 46 PM" src="https://user-images.githubusercontent.com/31829033/222924276-ef61cc80-b17a-4ea8-a646-289f32ed22ad.png">

Is it possible that build is deprecated?

**Comment by fangq** [comment]
hi @PyMarc2, thanks for reporting this. I have added  instructions in the README in the above commit on how to start the app.

also similar to this highlighted section in our workshop setup guide

http://mcx.space/wiki/index.cgi?Workshop/MCX19Preparation#:~:text=Special%20instructions%20for%20Mac,will%20get%20an%20error.

this is a screenshot on an older mac (10.13). let me know if the same trick works on 12.4

![mcxstudio_mac](https://user-images.githubusercontent.com/226913/223877714-666e56c8-3656-4230-be2b-027fe3670ce2.png)
