### ISSUE TITLE
Misleading Documentation for Gaussian Source Type

### ISSUE THREAD

**Issue by faberno** [fangq/mcx#165]
In mcxlab.m the comments say that the gaussians waist radius should be specified in voxels.
https://github.com/fangq/mcx/blob/b78c4e39b92dcad94abb62eadeffc5711a702a03/mcxlab/mcxlab.m#L146

In mcx_const.h it says that it should be in sigma.
https://github.com/fangq/mcx/blob/b78c4e39b92dcad94abb62eadeffc5711a702a03/src/mcx_const.h#L78

I did a experiment and specifying it in sigma should be the correct way. So it would probably be good to change that in mcxlab.h.
It also says that the hyperboloid gaussians waist should be in voxels, but there I didn't check if its wrong too.

**Comment by fangq** [comment]
sorry, forgot to attach the output from the below test code
```
clear cfg
cfg.nphoton=1e7;
cfg.vol=uint8(ones(60,60,60));
cfg.gpuid=1;
cfg.autopilot=1;
cfg.prop=[0 0 1 1;0.005 1 0.8 1.37];
cfg.srctype='gaussian';
cfg.srcpos=[30 30 -10];
cfg.srcdir=[0 0 1];
cfg.srcparam1=[10 0 0 0];
cfg.srcparam2=[0 0 0 0];
cfg.tstart=0;
cfg.tend=5e-11;
cfg.tstep=5e-11;
flux=mcxlab(cfg);
fcw=flux.data*cfg.tstep;
plot(squeeze(fcw(cfg.srcpos(1),:,1)))
grid on;
```

the 1D profile across the source shows the `cfg.srcparam1.x=10` specifies the waist of the beam, which is 2*sigma.

![Gaussian_src](https://user-images.githubusercontent.com/226913/234388291-b85a784e-aeed-42f1-9f43-4934678e0499.png)
