### ISSUE TITLE
About comments of 2nd command 

### ISSUE THREAD

**Issue by lxuc** [fangq/mcx#20]
In your readme file, you mentioned that "the 2nd command above will launch 2048 GPU threads (-t) with every 64 threads a block (-T); "

The 2nd command is: 
             mcx -t 16384 -T 64 -n 1e7 -f input.inp -s test -r 2 -g 10 -d 1 -b 1 -G 1

The thread number is 16384, not 2048.
I am confuse about it.

Thanks

**Comment by fangq** [comment]
thanks for pointing out the typo, this is now fixed.

https://github.com/fangq/mcx/commit/b744b31e1a2e461d456948c5674cfec76a3ed9ac
