### ISSUE TITLE
mcxlab: Where to find "sphdiffusionslab.m" required by "demo_validation_heterogeneous.m"?

### ISSUE THREAD

**Issue by binlbl** [fangq/mcx#201]
I can not run mcxlab demo "demo_validation_heterogeneous.m" , where is the required file "sphdiffusionslab.m"?

Thanks!

**Comment by fangq** [comment]
please read the error message - the file is located in the mmc package under the mmc/matlab folder

https://github.com/fangq/mcx/blob/28e510130e6075b7a1b68b45f77973a154437a7d/mcxlab/examples/demo_validation_heterogeneous.m#L19

https://github.com/fangq/mmc/tree/master/matlab
