### ISSUE TITLE
Different scattering coefficient of water in demo_skinvessel.m compared to mcxyz.c

### ISSUE THREAD

**Issue by binlbl** [fangq/mcx#204]
Dear Dr. Fang,

I noticed you use a different scattering coefficient for water in demo_skinvessel.m in mcxlab compared to mcxyz.c .
You use '1', while mcxyz.c use '10' for scattering coefficient for water. 
Does it matter?

Thank you very much!

**Comment by fangq** [comment]
it does not matter because g is set to 1, so photons won't scatter, just forward stepping. Please see the description of the g value in mcxyz's website
https://omlc.org/software/mc/mcxyz/
