### ISSUE TITLE
pmcx dettpsf overwrites input detp structure

### ISSUE THREAD

**Issue by rachelcomind** [fangq/mcx#208]
The input `detp` structure is overwritten by `dettpsf`. This means that calling `dettpsf` twice for two different detectors always returns a null result for the second detector.

![image](https://github.com/fangq/mcx/assets/119049550/3a6fc06d-a8cc-4542-9872-a691897e3105)

**Comment by fangq** [comment]
@rachelcomind, thanks for reporting this, my student @fanyuyen is working on a fix, will close this ticket when the patch is committed.

@fanyuyen, please create a PR when ready. please use `black` to reformat the code once updated. thanks
