### ISSUE TITLE
Replay fails when simulating with multiple light sources

### ISSUE THREAD

**Issue by shanghongY** [fangq/mcx#215]
When using two Gaussian light sources, there is an error in saving the detected photon ID, and the photon replay function fails to replay all the photons, as shown in the figure. In addition, I also calculated the photon energy absorption, and when using the formula of optical path length and absorption coefficient, the energy absorption of the detected photon is different from the simulation. However, when the same operation is performed with a single light source, the results are correct. Is it possible to solve this problem? Thank you very much.

![HP0 $NBGZWZIAU2MXU_@JUW](https://github.com/fangq/mcx/assets/163225517/66b563a2-9ad7-4cd6-82ac-aba3f9a909ed)
![CT13R9 7$ EPFZG212O`OWN](https://github.com/fangq/mcx/assets/163225517/66293a33-2b92-46be-a076-b6bff25cf827)
![EM94(RUI%O~$HH$%(RJ @KC](https://github.com/fangq/mcx/assets/163225517/bee84ff4-9001-46af-b162-5e572885599d)
![VZX2 7_K_YR~5~4U3)@`Q8E](https://github.com/fangq/mcx/assets/163225517/fa1d0ca5-3650-4990-bef6-9f2903cf9a16)

**Comment by shanghongY** [comment]
![CT13R9 7$ EPFZG212O`OWN](https://github.com/fangq/mcx/assets/163225517/76fb72ba-62c0-48cd-a01a-379c5a995db8)
![EM94(RUI%O~$HH$%(RJ @KC](https://github.com/fangq/mcx/assets/163225517/fe19c6d9-3da8-4c81-bf05-420d7a84b7e5)

**Comment by fangq** [comment]
sorry, I do not follow your report, especially the meanings of the circles in Fig. 2 and Fig4. I also do not fully understand what was the error you saw.

can you please edit your report's title, specify what was the issue you are trying to get an answer.

if this involves multiple issues, please describe those in an itemized fashion, providing evidence for each item

**Comment by shanghongY** [comment]
Thank you for your reply. My problem is photon replay failure when simulating with two Gaussian light sources. In the simulation using 10 million photons, 5173 photons are detected by the detector, but only 2598 photons are detected by the photon replay. When calculating the energy absorption of these 5173 photons, it is 92.628% by the formula, and the simulation result is 68.6%. However, when modified to a Gaussian light source, the results are consistent.
![5DGVMA%YU`06)NDM(9OFNU1](https://github.com/fangq/mcx/assets/163225517/f5d44291-251b-4816-b8db-525038791cee)

**Comment by shanghongY** [comment]
FIG. 1 and FIG. 2 are the simulation results of photon replay when two Gaussian light sources and a single Gaussian light source are used, respectively. Thank you very much.
![0FE) (ML`K~{308A2CYGCEH](https://github.com/fangq/mcx/assets/163225517/e5e4df53-e995-48ce-aee9-e245be9414e4)
![20240313120844](https://github.com/fangq/mcx/assets/163225517/b49bfad0-45f4-4806-9eec-ed89c82ae848)

**Comment by fangq** [comment]
thanks @shanghongY, I got it. I also understood why this happened, and just [committed a fix](https://github.com/fangq/mcx/commit/abdee14c6dc183eae31cb44b60359ebf2d5fc46e).

please wait for the [action script to complete](https://github.com/fangq/mcx/actions/runs/8259364453/job/22593201590), go download the new binary [from here](https://mcx.space/nightly/github/), and test this again, hopefully it is resolved.

**Comment by shanghongY** [comment]
Thank you very much for your support.

**Comment by shanghongY** [comment]
I'm sorry to bother you again. I downloaded the updated GitHub version of mcx(Figure 1), but I can't seem to open mcxstudio directly. The version of win64 I downloaded in the past can be opened directly. Thank you very much.
![_931}(L9 05W2ZTX7AGB6I8](https://github.com/fangq/mcx/assets/163225517/4a9d3534-6275-4266-8331-56018cf15e26)
