### ISSUE TITLE
Bug in source type "disk"

### ISSUE THREAD

**Issue by bernhardkaplan** [fangq/mcx#26]
When using the source type "disk" the launched photon density has a dip in the center of the circle and along the radial axis.
![output_300x300](https://cloud.githubusercontent.com/assets/1629580/18344881/65471130-75b9-11e6-82a7-99ce8b98090d.png)
The output has been generated using [this json parameter file](http://www.filedropper.com/8benchmark-diskmodified)

The volume file is:
`
{
  "Shapes": [
     {"Name":     "cubic300"},
     {"Origin":   [0,0,0]},
     {"Grid":     {"Tag":1, "Size":[300,300,60]}}
  ]
 }
`
and the run command:
`mcx -A -f 8benchmark-disk_modified.json -r 100 -b 1 8benchmark-disk_modified "$@"`

Python plot script is [here](http://www.filedropper.com/plotbenchmarkresults)

**Comment by fangq** [comment]
close, no longer reproducible. if the issue remains under certain conditions, feel free to reopen.

**Comment by fangq** [comment]
possibly this was also caused by the low precision Windows rand() function, see Issue #31 and the fix.
