### ISSUE TITLE
Trajectory saving only works with mcxlab

### ISSUE THREAD

**Issue by kel85uk** [fangq/mcx#35]
At the moment, it seems that within mcx_core.cu, cfg->exportdebugdata does nothing but saves the photon trajectories. After that, the user needs mcxlab to visualize and process the debug information. It would be good to have it directly within the mcx executable which creates a debug file with the necessary trajectory information.

**Comment by fangq** [comment]
this is now supported in the command line as well (included in mcx 1.0). trajectory data are saved as an .mct file, which can be load using loadmch(), like the history file.

https://github.com/fangq/mcx/commit/e99e5ef24cd0ac1507a6f8cd36804cc72b7d6d4d

closing the tracker.
