### ISSUE TITLE
Improve Volume Rendering Preview of Light Sources in MCXStudio

### ISSUE THREAD

**Issue by MengXiangxi** [fangq/mcx#36]
Currently, the "preview" function in the volume designer of MCXStudio could only visualize some of the different types of light sources, including Pencil, Disk, Gaussian, and etc. Some other types of source are either not shown or incorrectly represented.

**Comment by fangq** [comment]
@MengXiangxi, here is the listed sources that are currently rendered:

https://github.com/fangq/mcx/blob/master/mcxstudio/mcxrender.pas#L602-L611

adding the point-sources (pencil, isotropic, arcsine) which can only be shown as a point, I believe the currently unsupported sources are

- cone
- line
- slit
- pencilarray

does this match your expectations? is there a particular type of source that you want to be implemented first?

**Comment by fangq** [comment]
cone, line and slit sources are now supported in the render.
