### ISSUE TITLE
Question about light source

### ISSUE THREAD

**Issue by ckolluru** [fangq/mcx#37]
Dr. Fang,

Thank you for this software. I'd like to know if there is a way to configure the photon fluence rate of the source?

Thanks,
Chaitanya

**Comment by fangq** [comment]
hi Chaitanya, 

MCX/MMC gives you the Green's function. That means the intensity of the source is assumed to be 1 (unitary). However, fluence is linearly proportional to the intensity of the source. so if your source have a different intensity, you simply multiply the solution by your source intensity.

let me know if this answers your question.

**Comment by ckolluru** [comment]
Dr. Fang,

Thank you for your reply. I wanted to know if it is possible to initiate photon packets from the source at different time points and not as an instantaneous pulse at time t=0. Also, would I be able to simulate an optical coherence tomography acquisition with this software? If not, could you point me to possible alternatives?

Thank you,
Chaitanya

**Comment by fangq** [comment]
that is also support if you utilizes the properties of the Green's function (i.e. TPSF if in the time-domain). If you have an arbitrary waveform for the source, all you need to do is to convolve that source waveform with the TPSF at every location derived from MCX/MMC.
