### ISSUE TITLE
photon angle (z direction) issue in mcxlab

### ISSUE THREAD

**Issue by fangq** [fangq/mcx#38]
submitted by @yaoruoyang:

In mcxlab, the output angle of a small number of photons (along z direction) have the wrong sign, we need to fix that (not sure about the cause).

Also, there's a small possibility that the angle of z is NaN (when the sum square of x angle and y angle is close to 1), this is very likely caused by the rounding number issue.

Please use the attached scrip to reproduce the issue and for debugging.

```
% In mcxlab, the output angle of a small number of photons (along z direction)
% have the wrong sign, we need to fix that (not sure about the cause)

% Also, there's a small possibility that the angle of z is NaN (when the
% sum square of x angle and y angle is close to 1), this is very likely
% caused by the rounding number issue.

%% test 1, reflection mode

clear cfg cfgs
cfg.nphoton=1e9;
cfg.vol=uint8(ones(60,60,60));
cfg.srcpos=[29.5, 29.5, -0.01];
cfg.srcdir=[0 0 1];

cfg.gpuid=1;
cfg.autopilot=1;

cfg.prop=[0 0 1 1;0.005 1 0 1.37];

cfg.tstart=0;
cfg.tend=5e-9;
cfg.tstep=5e-9;

cfg.issrcfrom0=1;
cfg.isreflect=1;
cfg.issaveexit=1;

cfg.detpos = [29.5, 39.5, -0.01, 3];

% calculate the flux distribution with the given config
[flux1,detp1,~,~] = mcxlab(cfg);

count1 = length(find(detp1.v(:,3)>0));
count2 = sum(isnan(detp1.v(:,3)));

%% test 2, transmission mode

clear cfg cfgs
cfg.nphoton=1e9;
cfg.vol=uint8(ones(60,60,20));
cfg.srcpos=[29.5, 29.5, -0.01];
cfg.srcdir=[0 0 1];

cfg.gpuid=1;
cfg.autopilot=1;

cfg.prop=[0 0 1 1;0.005 1 0 1.37];

cfg.tstart=0;
cfg.tend=5e-9;
cfg.tstep=5e-9;

cfg.issrcfrom0=1;
cfg.isreflect=1;
cfg.issaveexit=1;

cfg.detpos = [29.5, 29.5, 20.01, 3];

% calculate the flux distribution with the given config
[flux2,detp2,~,~] = mcxlab(cfg);

count3 = length(find(detp2.v(:,3)<0));
count4 = sum(isnan(detp2.v(:,3)));

```

**Comment by fangq** [comment]
the nan issue is now fixed. it was due to the transmission function - I thought testing Rtotal<1 is enough to ensure the sqrt() is always positive inside, but this was not true after multiplying n1/n2. 

the negative z-dir sign issue is not fixed though. This is a bigger problem - it appears that my algorithm for determining flipdir is problematic. for the incorrect direction vector outputs, the flipdir is 0, 1 or 2, and never 3 (meaning that passing by the z-plane, which is what we expected). 

this need to modify hitgrid and determine flipdir more rigorously.

**Comment by yaoruoyang** [comment]
I tried mmclab quite a few times and don't see similar photon angle issues there. Maybe by comparing the implementation of flipdir in mmc/mcx we are able to find something.

**Comment by fangq** [comment]
yes, flipdir is unique to mcx - because in mcx, the boundary is always parallel to x/y/z plane. 

here is a sample subset of the problematic photons from your test script:

```
        px        py         pz         flipdir         vy          vz
  27.9998779  36.9893112  -0.0000505           0   0.9087040   0.2857881
  26.9998779  39.1745987  -0.0000450           0  -0.3674004   0.4359206
  27.9998779  39.1239052  -0.0000027           0   0.3945841   0.5882843
  31.4349670  41.0001221  -0.0000350   1.0000000   0.6205006   0.2128905
  28.9998779  38.4230690  -0.0000168           0   0.0702995   0.6735473
  30.4717197  37.0001221  -0.0000498   1.0000000   0.5363353   0.6355564
  28.9998779  38.2464218  -0.0000009           0  -0.8422259   0.2530095
  30.3554649  38.5345802  -0.0000204   2.0000000   0.6326571   0.6573589
  29.9998779  41.9801216  -0.0000196           0   0.5621805   0.0599955
  29.9998779  38.4932899  -0.0000314           0  -0.6609473   0.3100340
```

for example, for the first photon, mcx determines that the photon exits the domain through x-plane (flipdir=0), but it looks like it actually has either already exited the domain through z-plane (because z is negative) before this step, or made a mistake.

it was these misjudged exit photons that causes the incorrect vz sign.

when plotting the positions, I also saw some scattered points that are not on the detector aperture. I don't think I've seen these before.

![bad_exit_positions](https://user-images.githubusercontent.com/226913/39601599-79e90d0c-4ef0-11e8-91d3-f9a3bde2ab68.png)

**Comment by fangq** [comment]
problem fixed. I revert the code back to various previous versions, and found out that the issue appears after commit 95b4370, and the only line in that commit related to this is unset isdet value when a photon moves outside of the bounding box. After placing this line back, the erroneous detected photons are gone.

closing the issue.
