### ISSUE TITLE
Scattering occurs with a zero scattering coefficient because of non-zero g

### ISSUE THREAD

**Issue by kdreher** [fangq/mcx#51]
For a non-scattering medium, I expected the photons to travel in straight lines from their respective light source. 
However, there seem to be some scattering events happening because of a non-zero g.
I appended one minimal example as a plot.

The file "test1.json" describes a pencil beam on the top of a non-scattering but absorbing medium heading straight into the medium (src_dir.z=-1).
The output showed photons mostly travelling in a straight line but some scattered deviations. 

![test1](https://user-images.githubusercontent.com/40358298/47565358-72a2ef00-d928-11e8-9f0e-968bfe83ff6a.png)

**Comment by fangq** [comment]
it should be fixed with the above committed patch, please let me know if you need to reopen this issue again.
