### ISSUE TITLE
Hi Dr

### ISSUE THREAD

**Issue by Li-Xue** [fangq/mcx#56]
I want to copy the methods from Minsu Kim's paper（Development of a laboratory spectral
backscattering instrument: design and simulation）and to  simulate  a photon from the incident beam hits the cuvette. Then I want to determine the optimal design of the backscattering measurement system. Please you give me some sugguestions if I use your software.

**Comment by Li-Xue** [comment]
Thanks a lot. 
I will spend some time to learn your software for my research. 
I hope I can solve my issues by studying your instructions and examples.

**Comment by fangq** [comment]
ok, I am going to close this issue for now, and if you have specific questions, feel free to reopen, or post it to our forum https://groups.google.com/forum/?hl=en#!forum/mcx-users
