### ISSUE TITLE
error in __init__.py

### ISSUE THREAD

**Issue by 4D42** [fangq/mcx#61]
Hello, first thanks for the source code and for all the work.

I was playing with the program and I just encounter an error using the python __init__.py file.

If I don't save the photons seed I encounter an error when I try to use the load_mch python function. It look like it come from the line 107 with the variable `photon_seed`

If I understand it correctly the line should be just after the line 85 `photon_seed.append(np.asarray(seeds).reshape((seed_byte,saved_photon), order='F'))` or after, just before `return mch_data, header, photon_seed` 

There is also some problem (or misunderstanding) with the `header` variable. `header.medium` dose not exist therefore is `M = header[""maxmedia"]+1`

**Comment by fangq** [comment]
let me know if the above fix solves the issue. if not, please reopen.

**Comment by 4D42** [comment]
It work great. Thank you!
