### ISSUE TITLE
How to interpret index of photon packet in Trajectory output（.mct file)?

### ISSUE THREAD

**Issue by QxaSJTU** [fangq/mcx#74]
Hi, in your 2018-08-14 [e99e5ef] release, you  allow saving photon trajectory in command line.
However, I have trouble understanding the first column of the output (index of photon packet). 
Instead of distinguish each packet with a unique index, the index is in order of 10^42 and not monotonically increasing.
Please tell me how to understand these index, thank you very much!

**Comment by fangq** [comment]
the first number is the index (from 1 to #total simulated photon). it is an integer, but if you read the file using loadmch.h, the field is treated as float, and you will have to use typecast(data(:,1),'uint32') to cast it back to integers. 

if you use mcxlab instead, this conversion is done internally

https://github.com/fangq/mcx/blob/master/mcxlab/mcxlab.m#L406
