### ISSUE TITLE
How to build a GPU server for MCX simulation

### ISSUE THREAD

**Issue by xwimming** [fangq/mcx#78]
Hello
We are planing to build a GPU server for our MCX simulation. However, we have difficulties to create containers properly and assign to user. Would someone help us, such as a quick guide? Thank you.

**Comment by fangq** [comment]
@xwimming, most of my severs were set up for local users (Ubuntu 16.04/18.04 with the latest NVIDIA GPU driver).

if you have to use container, I suggest you to take a look at the below document. My student @leimingyu created some mcx docker images a few years ago. I am not sure it those still works, but the instruction document may still be helpful.


[docker_nvidia_mcx.pdf](https://github.com/fangq/mcx/files/3610637/docker_nvidia_mcx.pdf)
[download_image.sh.txt](https://github.com/fangq/mcx/files/3610640/download_image.sh.txt)

**Comment by xwimming** [comment]
How to set up for local users? I thought I have to create container or docker and assign to users in order to use the GPU server on other computers.

**Comment by xwimming** [comment]
Hello Dr.Fang. I installed openssh and the NVIDIA GPU driver 390.116 to our server. I can use PuTTY to remote the server. I tried to use MCX to remote the GPU in the server, but the output for 'Printing GPU Information' is 'bash: mcx: command not found' and no GPU information showed up. The GPU in the server is GeForce GT 730. Should I install something else into the Ubuntu 18.04 server version?
