### ISSUE TITLE
MCXpreview Graphical Issue

### ISSUE THREAD

**Issue by dcohen45** [fangq/mcx#79]
In the matlab version of MCX there is a graphical issue when using MCXpreview. When using the 'planar' source type, the orientation of the planar source is dependant on the source direction and as a result does not correspond with the actual location used in the simulation. This can be seen when the trajectories of the photons are superimposed with the mcxpreview. I have attached an image for reference. 
![MCXpreviewWithTrajectories](https://user-images.githubusercontent.com/55286304/64870077-99d1e000-d610-11e9-8d87-ccb940d870a1.png)

**Comment by fangq** [comment]
interesting, do you mind sharing our script? happy to take a look

**Comment by fangq** [comment]
should be fixed by @kaoben2731's patch 
https://github.com/fangq/mcx/pull/100

closing now. if issue remains, feel free to reopen.
