### ISSUE TITLE
memory error on Win 10 with registry fix :(

### ISSUE THREAD

**Issue by kuilef** [fangq/mcx#81]
Dear community (and Dr. Fang) I have a problem with memory

> MCXLAB ERROR -4 in unit mcx_core.cu:2096: unspecified launch failure
> Error from thread (0): unspecified launch failure
> C++ Error: MCXLAB Terminated due to an exception!

Win 10 x64, applied the registry fix.

The problem is that I have just 166*42*54 px volume (cutted from fullhuman_atlas.mat) and it works with max number of cfg.nphoton= 7e7

That is strange, because I have 4xGe Force GTX 1080Ti and 64Gb memory and tried cfg.gpuid= '1111' and cfg.gpuid= '0111' and others lige cfg.gpuid=2 etc.

Is it possible to get 1e8, 1e9 etc with Windows and USC_atlas volume?
Even on examples/mcx_gpu_benchmarks.m I am getting the same error :(

**Comment by fangq** [comment]
if you drop photon numbers and do not see this error,  I am pretty sure the registry fix was not activated.
you may want to check the TdrDelay value again (make it big), and also must reboot the machine after changes.

**Comment by kuilef** [comment]
Thank you very much, you're totally right - strangely, registry fix was not activated, I added it manualy and magically - it works!

**Comment by fangq** [comment]
great!
