### ISSUE TITLE
registration information gone public

### ISSUE THREAD

**Issue by lzjk** [fangq/mcx#84]
Hi 

I just found that my registrations information including  name, institution and email can be publicly viewed at the webpage :  http://mcx.space/wiki/index.cgi?action=history&id=Registration/MCX

May I ask if this is a bug? Could you please hide these information?
Thank you.

**Comment by fangq** [comment]
@lzjk, I apologize for this information leak, I managed to fix this page permission bug in my wiki script, see

https://github.com/fangq/habitat/commit/2ad8252b2a72f8157385cc3c99045e053de28aed

and it should now prevent people from reading the content of this page. 

let me know if you see anything else that I need to fix. thanks for bringing this to my attention.

**Comment by lzjk** [comment]
That's great. Thank you for your prompt reply.
