### ISSUE TITLE
About runing demo_digimouse_sfdi.m

### ISSUE THREAD

**Issue by sunshine2004** [fangq/mcx#92]
Hi,

When I try to run the code, it seems frozen. The printed information is attached.
But everything goes fluently with cfg.nphoton=1e4. To confirm this is not related to Tdr_delay setting, I ran demo_4layer.m with cfg.nphoton=5e7 and it worked well.

demo_digimouse_sfdi
Launching MCXLAB - Monte Carlo eXtreme for MATLAB & GNU Octave ...
Running simulations for configuration #1 ...
mcx.dim=[190 496 104];
mcx.mediabyte=1;
mcx.medianum=22;
[31mWARNING: redundant field 'disk'
[0mmcx.srcpos=[50 200 100];
mcx.srcparam1=[500 0 0 0];
mcx.srcdir=[0 0 -1 0];
mcx.tstart=0;
mcx.tend=5e-09;
mcx.tstep=5e-09;
mcx.nphoton=100000;
mcx.autopilot=1;
mcx.gpuid=1;
mcx.unitinmm=0.8;
mcx.debuglevel='4';
###############################################################################
#                      Monte Carlo eXtreme (MCX) -- CUDA                      #
#          Copyright (c) 2009-2019 Qianqian Fang <q.fang at neu.edu>          #
#                             http://mcx.space/                               #
#                                                                             #
# Computational Optics & Translational Imaging (COTI) Lab- http://fanglab.org #
#            Department of Bioengineering, Northeastern University            #
###############################################################################
#    The MCX Project is funded by the NIH/NIGMS under grant R01-GM114365      #
###############################################################################
$Rev::1c0fd1$2019.4 $Date::2019-04-25 06:31:49 -04$ by $Author::Qianqian Fang $
###############################################################################
- variant name: [Fermi] compiled by nvcc [7.5] with CUDA [7050]
- compiled with: RNG [xorshift128+] with Seed Length [4]

GPU=1 (GeForce GTX 1060) threadph=4 extra=18080 np=100000 nthread=20480 maxgate=1 repetition=1
initializing streams ...	init complete : 9 ms
requesting 1024 bytes of shared memory
launching MCX simulation for time window [0.00e+00ns 5.00e+00ns] ...
simulation run# 1 ... 
Progress: [>

**Comment by sunshine2004** [comment]
I have additionally tested the code with a GTX-1070 card but still failed to run.
This code can be ran with a previous MCX version uploaded in 2018.

**Comment by fangq** [comment]
@sunshine2004, did you figure it out? 
I was about to suggest you to comment out this line

https://github.com/fangq/mcx/blob/master/mcxlab/examples/demo_digimouse_sfdi.m#L63

I found that printing progress bar was not entirely reliable on different GPUs and driver versions. Let me know if this issue remains.

**Comment by sunshine2004** [comment]
Dear Prof. Fang,

Thanks for your kind reply.
Yes, I figured it out when I deleted ‘cfg.debuglevel='P';’ 😊
Not sure what happened there, but everything works now.

Thanks again and stay safe,
Mengyu
