### ISSUE TITLE
About pattern3d source

### ISSUE THREAD

**Issue by sunshine2004** [fangq/mcx#93]
I cannot get anything when using this source. I found a similar report https://github.com/fangq/mcx/issues/77#issue-488554139

**Comment by sunshine2004** [comment]
I tried with GTX1060, GTX1070 and RTX2080. None of them works with this code

**Comment by fangq** [comment]
what version of mcxlab are you using? did you try the [nightly build](http://mcx.space/nightly/)?

I don't have any issue running the sourcetype demo using the latest mcxlab, including pattern3d sources, see screenshot 

![sourcetype_demo](https://user-images.githubusercontent.com/226913/80871219-96f82e00-8c79-11ea-963a-499701318f5a.png)

**Comment by fangq** [comment]
I am closing this for now. Feel free to reopen if the issue reappears.
