### ISSUE TITLE
Question about MCXLAB pattern source output

### ISSUE THREAD

**Issue by kaoben2731** [fangq/mcx#97]
Hello,

I'm trying to use the pattern source in MCXLAB.
I can run the demo_photon_sharing.m script properly.
However, when I want to use it on my simulation, the output flux is 0 for every voxel, although the status shows there are some absorbed energy, and the output at command window also shows that.
(fluencerate is the variable I'm using to store the output flux)
![Screenshot from 2020-05-20 20-39-41](https://user-images.githubusercontent.com/26135032/82448006-aed60b80-9adb-11ea-82a7-1a80eeb3fffc.png)

```
Launching MCXLAB - Monte Carlo eXtreme for MATLAB & GNU Octave ...
Running simulations for configuration #1 ...
mcx.nphoton=2e+06;
mcx.dim=[253 192 148];
mcx.mediabyte=1;
mcx.srcpos=[16.3962 164.282 58.5155];
mcx.srcdir=[0.776948 -0.45776 -0.432212 0];
mcx.srctype='pattern';
mcx.srcpattern=[45 45 1];
mcx.srcnum=1;
mcx.srcparam1=[16.7573 -9.87302 40.5797 45];
mcx.srcparam2=[-22.843 -38.7711 -0 45];
mcx.detnum=6;
mcx.gpuid=1;
mcx.tstart=0;
mcx.tend=5e-09;
mcx.tstep=5e-09;
mcx.isnormalized=1;
mcx.unitinmm=0.93;
mcx.savedetflag='53';
mcx.maxdetphoton=4e+06;
mcx.isgpuinfo=0;
mcx.autopilot=1;
mcx.issrcfrom0=1;
mcx.issaveexit=1;
mcx.issaveref=1;
mcx.isreflect=1;
mcx.isspecular=1;
mcx.medianum=8;
mcx.seed=868582;
WARNING: detector 1 is not located on an interface, please check coordinates.
WARNING: detector 2 is not located on an interface, please check coordinates.
WARNING: detector 3 is not located on an interface, please check coordinates.
WARNING: detector 4 is not located on an interface, please check coordinates.
WARNING: detector 5 is not located on an interface, please check coordinates.
WARNING: detector 6 is not located on an interface, please check coordinates.
###############################################################################
#                      Monte Carlo eXtreme (MCX) -- CUDA                      #
#          Copyright (c) 2009-2019 Qianqian Fang <q.fang at neu.edu>          #
#                             http://mcx.space/                               #
#                                                                             #
# Computational Optics & Translational Imaging (COTI) Lab- http://fanglab.org #
#            Department of Bioengineering, Northeastern University            #
###############################################################################
#    The MCX Project is funded by the NIH/NIGMS under grant R01-GM114365      #
###############################################################################
$Rev::1c0fd1$2019.4 $Date::2019-04-25 06:31:49 -04$ by $Author::Qianqian Fang $
###############################################################################
- variant name: [Fermi] compiled by nvcc [7.5] with CUDA [7050]
- compiled with: RNG [xorshift128+] with Seed Length [4]

GPU=1 (GeForce RTX 2060) threadph=65 extra=3200 np=2000000 nthread=30720 maxgate=1 repetition=1
initializing streams ...	init complete : 9 ms
requesting 1920 bytes of shared memory
launching MCX simulation for time window [0.00e+00ns 5.00e+00ns] ...
simulation run# 1 ... 
kernel complete:  	763 ms
retrieving fields ... 	detected 0 photons, total: 0	transfer complete:	876 ms
data normalization complete : 905 ms
normalizing raw data ...	source 1, normalization factor alpha=127.837608
simulated 2000000 photons (2000000) with 30720 threads (repeat x1)
MCX simulation speed: 2673.80 photon/ms
total simulated energy: 1808862.18	absorbed: 44.05679%
(loss due to initial specular reflection is excluded in the total)
```

And my setting are below:
![Screenshot from 2020-05-20 20-35-56](https://user-images.githubusercontent.com/26135032/82448194-f9f01e80-9adb-11ea-8f55-8cd753b231bc.png)

The pattern I'm using is a 45*45 2D-Gaussian pattern.

I had tested another source type: the planar source, only change the srctype in the setting:
![Screenshot from 2020-05-20 20-42-00](https://user-images.githubusercontent.com/26135032/82448350-2efc7100-9adc-11ea-861d-56a1bc128f8d.png)

Then I got reasonable output
![Screenshot from 2020-05-20 20-41-30](https://user-images.githubusercontent.com/26135032/82447980-a54ca380-9adb-11ea-987f-38bad7f87428.png)

I also plot the flux I detected, the distribution seems reasonable to me.
![Screenshot from 2020-05-20 20-55-52](https://user-images.githubusercontent.com/26135032/82449007-20628980-9add-11ea-8d90-89cbcb1bb94b.png)

Want to know if I made some mistake.

Thanks for helping!

**Comment by fangq** [comment]
@kaoben2731, did you check your `srcparam1` and `srcparam2` settings? the dimensions of the arrays must be stored in these two inputs, see

https://github.com/fangq/mcx/blob/master/mcxlab/mcxlab.m#L132-L137

also, did you try the `gaussian` source type?
https://github.com/fangq/mcx/blob/master/mcxlab/mcxlab.m#L129

**Comment by kaoben2731** [comment]
@fangq 

Thank you for your quick reply.

My setting is 
```
mcx.srcparam1=[16.7573 -9.87302 40.5797 45];
mcx.srcparam2=[-22.843 -38.7711 -0 45];
```
The 4th parameter should be the dimension of the source patter,
and my pattern is 45*45, so I think this is consistent.

> also, did you try the gaussian source type?  

I had tried that, but I need a Gaussian distribution with a limited radius, as below:
![Screenshot from 2020-05-19 17-41-50](https://user-images.githubusercontent.com/26135032/82453390-0cba2180-9ae3-11ea-8d6c-622bb2f891c0.png)
Thus I'm trying to use pattern source.

> also, it looks like your background media is not 0

Thanks for pointing that out, I doesn't set the background to 0 intentionally, to check the photon distribution outside the tissue.

**Comment by fangq** [comment]
> The 4th parameter should be the dimension of the source pattern, and my pattern is 45*45, so I think this is consistent.

can you plot the domain by calling `mcxpreview(cfg)`? 

if the source location looks fine, then, I think the issue must be your pattern data - mcxlab expects it to be a [double-precision array](https://github.com/fangq/mcx/blob/master/src/mcxlab.cpp#L699) between 0-1, please check your pattern data.

if this still does not solve the problem, please send me your cfg data in a .mat so I can test.

**Comment by kaoben2731** [comment]
@fangq 

The preview figure are below:
![mcxpreview](https://user-images.githubusercontent.com/26135032/82489597-828ab100-9b14-11ea-9820-0b45ef75b7be.PNG)
Although the orientation of the quadrilateral is weird, I think the location of the source and detectors are same as I set,

My pattern is a double array between 0 and 1.
![image](https://user-images.githubusercontent.com/26135032/82490205-83701280-9b15-11ea-969b-a46945fadb5a.png)

I also find some weird things:
(All the cfg using below are the same.)
When I called this command, I can get the absorbed energy in voxel.
![mcxlab_command](https://user-images.githubusercontent.com/26135032/82490335-b1eded80-9b15-11ea-8e0d-0285f3533f66.PNG)
![mcxlab_command_2](https://user-images.githubusercontent.com/26135032/82490339-b3b7b100-9b15-11ea-9d65-13beac5719ef.PNG)

But if I also want to get the detected photon and the seed, I cannot get absorbed energy.
![mcxlab_command_3](https://user-images.githubusercontent.com/26135032/82490404-c7fbae00-9b15-11ea-947d-16e986bff5ad.PNG)
![mcxlab_command_4](https://user-images.githubusercontent.com/26135032/82490410-c8944480-9b15-11ea-95c2-c7795721e6ce.PNG)

I tested these command on my other computer, but both command cannot give me the absorbed energy.
![mcxlab_command_5](https://user-images.githubusercontent.com/26135032/82490543-02fde180-9b16-11ea-94b8-c35330262893.PNG)
![mcxlab_command_6](https://user-images.githubusercontent.com/26135032/82490537-01341e00-9b16-11ea-82cf-b179f0a1944f.PNG)
![mcxlab_command_7](https://user-images.githubusercontent.com/26135032/82490539-02654b00-9b16-11ea-8416-ed93bcf61ada.PNG)
![mcxlab_command_8](https://user-images.githubusercontent.com/26135032/82490541-02654b00-9b16-11ea-9ba4-a521aad27123.PNG)

Not sure if this is related to my problem.

My cfg file are below:
https://drive.google.com/file/d/1DF4PItpfyfjLRNpmx8iMKQd3XcwhsaS4/view?usp=sharing

Thanks again for your help!

**Comment by fangq** [comment]
from looking at the `mcxpreview` plot, I think you should check your `srcparam1/2` settings, as well as `srcdir`, and make sure that's what you want - `srcparam1(1:3)` and `srcparam2(1:3)` defines two vectors that span the two edges of the rectangle - usually, your launch direction, `srcdir`, is defined in perpendicular to this area. 

it looks to me that your srcdir is pointing to the bottom face and not casting light toward the head surface.

**Comment by kaoben2731** [comment]
@fangq 

I don't know why the points on the rectangle are all on the same z coordinate in the preview, and not consistent with the cfg setting.
![Screenshot from 2020-05-21 12-05-35](https://user-images.githubusercontent.com/26135032/82522309-93aae080-9b5b-11ea-9f75-d6373dd87451.png)
![Screenshot from 2020-05-21 12-09-02](https://user-images.githubusercontent.com/26135032/82522405-e84e5b80-9b5b-11ea-90a6-8f7e5a0cead9.png)


I calculate the Inner product of the vectors, and they seems almost perpendicular to each other
![image](https://user-images.githubusercontent.com/26135032/82522126-12534e00-9b5b-11ea-951d-2afdb2e430a1.png)

Isn't the red arrow represent the srcdir?  I think it is pointing to the head surface.
![image](https://user-images.githubusercontent.com/26135032/82522511-45e2a800-9b5c-11ea-8444-f60083614a43.png)
![image](https://user-images.githubusercontent.com/26135032/82522550-5e52c280-9b5c-11ea-8b59-c53750d3eb56.png)

**Comment by fangq** [comment]
@kaoben2731, is this remain a problem? if yes, can you provide me a script so that I can reproduce? thanks

**Comment by fangq** [comment]
closing - if the issue remains, feel free to reopen.
